#!/usr/bin/python3

import amulet
import unittest
import time


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='trusty')
        self.d.add('ubuntu', 'cs:trusty/ubuntu')
        self.d.add('elasticsearch', 'cs:trusty/elasticsearch-14')
        self.d.add('topbeat')
        self.d.relate('topbeat:beats-host', 'ubuntu:juju-info')
        self.d.relate('topbeat:elasticsearch', 'elasticsearch:client')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.elasticsearch = self.d.sentry['elasticsearch'][0]
        self.topbeat = self.d.sentry['topbeat'][0]

    def test_elasticsearch_host_in_templating(self):
        es_address = self.elasticsearch.relation('client', 'topbeat:elasticsearch')['private-address']  # noqa
        config = self.topbeat.file_contents('/etc/topbeat/topbeat.yml')
        self.assertTrue(es_address in config)

    def test_config_options(self):
        self.d.configure('topbeat',
                         {'procs': '^$',
                          'period': '187'})
        self.d.sentry.wait()
        # Changing the config variables just sets a "needs rendering" state.
        # The actual file is updated later so we need to wait a bit.... :(
        time.sleep(20)
        config = self.topbeat.file_contents('/etc/topbeat/topbeat.yml')
        self.assertTrue('^$' in config)
        self.assertTrue('187' in config)

if __name__ == "__main__":
    unittest.main()
