#!/usr/bin/python3

import amulet
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.kafka_host = '192.168.0.1:5044'
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('topbeat')
        self.d.relate('topbeat:beats-host', 'ubuntu:juju-info')
        self.d.configure('topbeat', {'kafka_hosts': self.kafka_host})

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.topbeat = self.d.sentry['topbeat'][0]

    def test_kafka_host_in_templating(self):
        config = self.topbeat.file_contents('/etc/topbeat/topbeat.yml')
        self.assertTrue(self.kafka_host in config)


if __name__ == "__main__":
    unittest.main()
